server:
  port: 80

spring:
  application:
    name: cloud-order-consul-service #服务名称

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
