server:
  port: 80 #端口号 注意这个服务开启就不要再开其他工程80端口了


#同样的注入到eureka注册中心中 并且eureka是集群
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  # 集群版
spring:
  application:
    name: cloud-order-openFeign-service #服务名称


#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
#指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000

#开启feign的日志打印功能
logging:
  level:
    com.huanglong.springcloud.service.PaymentFeignService: debug # feign日志以什么级别监控哪个接口
