server:
  port: 80
spring:
  application:
    name: sentinel-order  #服务器名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #注册进nacos
    sentinel:
      transport:
        dashboard: localhost:8080   #注册进sentinel
        port: 8719  #默认8719端口，加入端口被占用会自动从8719开始依次+1扫描 直到找到未被占用的端口
feign:
  sentinel:
    enabled: true #激活Sentinel对Fegin的支持 默认为false

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点
