server:
  port: 3344


##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  rabbitmq:  #配置rabbitmq
    password: 123456
    host: 192.168.17.144 #注意这个ip linux会变的
    port: 5672
    username: admin

  cloud:
    config:
      server:
        git:
          uri: https://github.com/2350029488/springcloud-config.git #GitHub上面的git仓库名字
          search-paths: #搜索目录（仓库）
            - springcloud-config
      label: main #读取分支
#      连起来就是哪个地址上面的哪个仓库下的哪个分支

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
