server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com  #eureka服务端的实列名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false      #不获取注册表 false表示自己就是注册中心，其职责就是维护服务实例e
    service-url:
                    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址  入住地址
#      defaultZone: http://localhost:7002/eureka/  单机是自己绑定自己 现在集群是绑定另外的一个注册中心7001
      defaultZone: http://eureka7001.com:7001/eureka/  #这只是注册地址，
  server:
    enable-self-preservation: false #关闭自我保护机制，保证不可用服务被及时踢除
    eviction-interval-timer-in-ms: 2000 #2秒进行一次驱逐
