server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service #服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #注册进nacos注册中心
    sentinel:
      transport:
        dashboard: localhost:8080  #配置sentinel dashboard仪表地址
        port: 8719  #默认8719端口，加入端口被占用会自动从8719开始依次+1扫描 直到找到未被占用的端口
        #把sentinel做持久化到nacos中
      datasource:
        dsl:
          nacos:
            server-addr: localhost:8848 #nacos ip
            dataId: cloudalibaba-sentinel-service #sentinel服务名
            groupId: DEFAULT_GROUP #默认分组
            data-type: json  #数据类型
            rule-type: flow #路由类型

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点

