server:
  port: 9527

#注册进eureka服务中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
spring:
  application:
    name: cloud-gateway  #服务名称

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址 动态路由  lb负载均衡
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
#    routes路由 就是 http://localhost:8001/payment/get/参数

        - id: payment_routh2    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址  lb负载均衡
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由

            #- Before=2020-02-05T15:10:03.685+08:00[Asia/Shanghai]
            #- Between=2020-02-02T17:45:06.206+08:00[Asia/Shanghai],2020-03-25T18:59:06.206+08:00[Asia/Shanghai]
            - After=2022-08-28T20:39:07.694+08:00[Asia/Shanghai]
#             #配置时间表示/payment/lb/请求在这个时间之后 ，之后  之间 才能访问
#            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Cookie=username,zzyy #携带cookie进行访问
#            - Method=GET  #表示时get请求才允许
