server:
  port: 7001

eureka:
  instance:
    hostname: localhost  #eureka服务端的实列名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false      #不获取注册表 false表示自己就是注册中心，其职责就是维护服务实例e
    service-url:
                    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaltZone: http://${eureka.instance.hostname}:${server.port}/eureka/
