server:
  port: 8001

  #  入驻进eureka注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 集群版
spring:
  application:
    name: cloud-provider-hystrix-payment #服务名称
